### ISSUE TITLE
BSP events cause soft reset.

### ISSUE THREAD

**Issue by hgijeon** [joric/bluetosis#10]
https://github.com/joric/bluetosis/blob/5742edd3701004fd5675435c472a29bb0c6d926a/firmware/main.c#L1317

I was wonder why the keyboard reset when I push bottom-left most key of right-half, and I found BSP events were caused by registered pin, which is shown at the link. I personally disabled the BSP event handler.

**Comment by joric** [comment]
I use that to erase bonds while powering on maybe? Are you sure it's resetting for no reason.
