### ISSUE TITLE
Gazell communication not works after BLE connection established.

### ISSUE THREAD

**Issue by hgijeon** [joric/bluetosis#11]
https://github.com/joric/bluetosis/blob/5742edd3701004fd5675435c472a29bb0c6d926a/firmware/mitosis_ble_gzll.h#L253

Gazell communication not works after BLE connection established. I think this is the priority or timing issue. For example, it works if I change the code like below.

> m_timeslot_request.params.earliest.priority = NRF_RADIO_PRIORITY_HIGH;

**Comment by joric** [comment]
Merged in #12
