### ISSUE TITLE
How to switch between keyboard sides

### ISSUE THREAD

**Issue by GreyOBox** [joric/bluetosis#14]
I made left and right side of keyboard.
Flashed firmware to left and right side (used `COMPILE_REVERSED` for left side firmware)
Switched on power for both sides and switched on BT in my phone. In BT devices browser I see two `Mitosis-BT` devices.
If I connect to one of them, like example to right side - I can start to use it, push buttons and type text. But second part of keyboard doesn't work. If I connect to it in BT devices browser too - it starts to work as right side too (so instead of `KC_Q` I see `KC_Y`). In result I don't have left side but have two right sides :)

* How to make one side to be left side?
* I have to see two `Mitosis-BT` devices anyway and connect to both of them?

I checked Wiki and source code - still can't get how to switch to left side.
Found only
> Press Adjust + ← ↓ ↑ → to switch between three Bluetooth devices and a receiver
> Press Fn + Adjust + ← ↓ ↑ → to reset three corresponding Bluetooth devices or erase all bonds

in https://github.com/joric/bluetosis/wiki/Layout and
> Pins that may be used for side autodetection:

in https://github.com/joric/bluetosis/wiki/Hardware
and can't find related information.

**Comment by joric** [comment]
can't you read
https://github.com/joric/bluetosis
"All fimware updates and softdevice go for the right half of the Mitosis keyboard, left half should be held intact."
