### ISSUE TITLE
fds read operations fails 

### ISSUE THREAD

**Issue by SimonMerrett** [joric/bluetosis#15]
I've adapted this to a matrix keyboard (using yj-14015) and am not able to read which ble gap address I am using. Did you run into any problems with the flash storage feature? I can't see any problem with your code.

**Comment by joric** [comment]
Nope. Don't really remember now. I was able to connect and to type. Receiver version should work. Check you're using proper memory placement in the ld file, those modules only have 16k RAM.
```sh
  FLASH (rx) : ORIGIN = 0x1b000, LENGTH = 0x25000
  RAM (rwx) : ORIGIN = 0x20002000, LENGTH = 0x2000
```

**Comment by SimonMerrett** [comment]
Thank you. I just double checked all the settings in https://github.com/joric/bluetosis/wiki/Building and they seem correct. Will close but comment if I find anything of interest.

**Comment by SimonMerrett** [comment]
I had another look at this today and on closer inspection, it was the write operation which was failing with `FDS_ERR_NO_SPACE_IN_FLASH` , so I introduced some `fds_gc()` and that seems to have done the trick.
