### ISSUE TITLE
Will this alternative NRF51822 module work? E73-2G4M04S1D

### ISSUE THREAD

**Issue by Cka3** [joric/bluetosis#2]
Hello and thank you for sharing your work! 👍 
I found this module [E73-2G4M04S1D](http://www.cdebyte.com/en/product-view-news.aspx?id=303)
![board](https://user-images.githubusercontent.com/5494349/47591674-203dee80-d979-11e8-9e24-491f7c225085.jpg)
Do you think this will work as a replacement for YJ-14015 and Core51822 (B)? 
Thanks

**Comment by joric** [comment]
There are QFAA chips (YJ-14015) that have only 16KB of RAM and QFAC chips (Core51822) that have 32KB. I  write and debug on YJ-14015 so it probably works with the other cheap modules as well.
