### ISSUE TITLE
Redox Wireless author

### ISSUE THREAD

**Issue by mattdibi** [joric/bluetosis#3]
Hi,
I'm sorry I just wanted to point out that here:
> Redox by /u/RedditSchloer (Redox Wireless a.k.a. codename Ultron) (Reddit)

you mentioned /u/RedditSchloer as the author of the [Redox Wireless](https://github.com/mattdibi/redox-keyboard/tree/master/redox-w) but actually these are two different projects from two different authors.
The Redox Wireless (aka codename Ultron) autor is /u/TiaMaT102 which is also the author of the original Redox.
I'm sorry I know it's nitpicking.

P.s. You did a fantastic job with the Bluetosis, I'm really impressed. Congrats!

**Comment by joric** [comment]
Cool. I only care about Wireless mod so I've changed the author to /u/TiaMaT102. Fixed in 4e23e8c6.

**Comment by mattdibi** [comment]
Thanks!
