### ISSUE TITLE
Crying about matrix scanning example 

### ISSUE THREAD

**Issue by Cka3** [joric/bluetosis#5]
Hello again,

Can you make an example with matrix scanning for all of us non-programmers, if you have time. At least with one row/column. I was trying to understand this code but I'm to dumb for this. It took me 3 days just to compile and flash my module.  
 
Thanks in advance.

**Comment by joric** [comment]
@Cka3 I don't have hardware at the moment. Maybe later. Maybe someone else helps.

There is also a project that uses diode matrix with Mitosis firmware:
* https://github.com/Durburz/interphase
* https://github.com/Durburz/interphase-firmware
