### ISSUE TITLE
High Power draw for the Bluetooth half

### ISSUE THREAD

**Issue by realSpok** [joric/bluetosis#6]
I have successfully flashed your software on my keyboard project, and I observed within 5-8mA of current consumption. (Even after power reset to exit debug mode)
The nrf51822 datasheet indicates that the chip should not draw more than a couple hundred micro amps, even with agressive advertising. 
Do you observe this too ?

**Comment by joric** [comment]
@realSpok cool, someone has noticed the project! I didn't know about power consumption the whole BLE+Gazell stuff was for the sake of emulating Mitosis receiver without reflashing the left half so it's not really a production quality. Maybe it's receiver's code fault, I don't really know yet. It's probably better to use BLEuart instead of Gazell.

**Comment by realSpok** [comment]
Ok. Thanks for the reply. I have opened a ticket on Nordics forums in parallel to try and see if it is normal:
https://devzone.nordicsemi.com/f/nordic-q-a/42456/8ma-current-draw-with-timeslot-api-ble-gazell-softdevice-130

I know that gazell in device mode are supposed to draw very little current, and indeed, the right half of my keyboard draws less than 100uA, but I could find nothing about the gazell host (left half for me). It may be normal for it to draw 8mA, since it is supposed to work as a dongle plugged into a computer, like the mitosis receiver. I will try to flash the mitosis receiver code when I have time, to see how much it draws, and update this ticket.

Did you have any other idea for getting the whole thing to work without BLE+Gazell ? I have been thinking that we could have the halves as 2 different BLE keyboards, ditching completely gazell. But that would mean no layers management between the 2 parts.

Thanks for your project, I have been working a lot with your codebase, my project is nearly functionnal with it !  I just need to sort this current consumption issue. My coin cell will not last long with 8mA draw.

**Comment by realSpok** [comment]
Something interesting that I found on the Nordic forums:
https://devzone.nordicsemi.com/f/nordic-q-a/41872/is-it-possible-to-run-gazelle-host-and-ble-concurrently/163115#163115

It seems advisable to run gazell as device on the BLE side. But I don't see how this would work for a keyboard.

**Comment by realSpok** [comment]
It is normal for the gazell host to draw this much. Closing the issue.

**Comment by realSpok** [comment]
It is normal for the gazell host to draw this much. Closing the issue.
