### ISSUE TITLE
Building on Linux + Making compatible with Chimera

### ISSUE THREAD

**Issue by Epictek** [joric/bluetosis#7]
What changes would need to be made to support a chimera keyboard? Obviously the keyboard layout would need to be updated but are there any other changes required? should I make PR if I make any progress with adding chimera support?

Also is the only way to build this on windows or is there an easy way to build on linux that you know off?

**Comment by joric** [comment]
Chimera is just a Mitosis clone with a different layout. Current version is mostly written and tested for GCC so you don't need Windows at all.
