### ISSUE TITLE
QK_LSFT for "shifted keycodes" not working.

### ISSUE THREAD

**Issue by pfoff** [joric/bluetosis#9]
First I want to thank you for the great work you've done. With the default keymap it seems to work pretty well!
Now I wanted to port my keymap from qmk and ran into problems. Keycodes like 
`#define KC_PIPE LSFT(KC_BSLS)`
do not work. I did understand that qmk features are not really included yet. But I am trying to build a fix for that one, but when I check the transmitted key in mitosis_ble_gzll.h
`  if( key & QK_LSFT )	{
	modifiers |= 1;
        key ^=  QK_LSFT;
  }`
but that does not seem to work. Maybe I should start to investigate on the debugging options. But I still hope that you could point me the right direction to get that working !-)

**Comment by joric** [comment]
I don't have the hardware now so I can't really debug the key scanning code, haven't looked at it for a while but it appears very basic (doesn't support compound keycodes) so there's a lot to add.

Speaking of full QMK support check this out:

https://github.com/sekigon-gonnoc/BLE-Micro-Pro
https://github.com/sekigon-gonnoc/qmk_firmware/tree/nrf52

This guy managed to add nRF5x to QMK as a separate hardware platform. I compiled it for ergo42_ble maybe you could make it work for Mitosis. Sure it would not be easy but that would be the real deal.

**Comment by pfoff** [comment]
Thanks for the suggestion! That way seems to be the best solution. But that means I have still a long way to go!-) Anyway I love the clean project you have created. Maybe I use it to learn about debugging nordic hardware.

**Comment by joric** [comment]
Added links to QMK fork and deprecation notice in 31693bf5.
